# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import e_ood_django.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_lower', models.CharField(blank=True, max_length=200, unique=True)),
                ('changelog_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('name_lower',),
            },
        ),
        migrations.CreateModel(
            name='PackageDBAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(verbose_name='Description of client')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'contains security fixes'), (3, 'contains non-security bug fixes'), (4, 'contains fixes for compatibility with some other software'), (5, 'contains only new features'), (6, 'version should be ignored'), (7, 'LTS release')])),
                ('version', models.CharField(max_length=20, validators=[e_ood_django.models.validate_version])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_ood_django.Package')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together=set([('package', 'version')]),
        ),
    ]
