# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_ood_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagedbaccess',
            options={'verbose_name_plural': 'package DB accesses'},
        ),
    ]
