# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_ood_django', '0002_auto_20180228_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='changelog_url',
            field=models.URLField(blank=True, verbose_name='Changelog URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_lower',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Name (lower-cased)'),
        ),
    ]
